<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>WindowsPackageManager.Interop</RootNamespace>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    
    <!-- IF BUILD FAILS DUE TO MISSING Microsoft.Management.Deployment NAMESPACE,
     TOGGLE THE LAST NUMBER OF THE LINE BELOW 1 UNIT UP OR DOWN, AND REBUILD-->
    <WindowsSdkPackageVersion>10.0.26100.57</WindowsSdkPackageVersion>
    
    <!--Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers-->

  </PropertyGroup>

  <!--
  CsWinRT properties:
  https://github.com/microsoft/CsWinRT/blob/master/nuget/readme.md
  -->
  <PropertyGroup>
    <CsWinRTWindowsMetadata>10.0.19041.0</CsWinRTWindowsMetadata>
    <CsWinRTIncludes>Microsoft.Management.Deployment</CsWinRTIncludes>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <CsWinRTInputs Include="$(PROGRAMFILES)\WindowsApps\Microsoft.DesktopAppInstaller_1.29.280.0_x64__8wekyb3d8bbwe" />
    <!--Content Include="$(TargetDir)\winrtact.dll" Link="winrtact.dll" CopyToOutputDirectory="PreserveNewest" /-->
  </ItemGroup>

  <ItemGroup>
    <Content Include="Microsoft.Management.Deployment.winmd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="2.2.0" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.228">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

    <!--
    Microsoft.WindowsPackageManager.ComInterop nuget targets .NET Framework:
    https://www.nuget.org/packages/Microsoft.WindowsPackageManager.ComInterop#readme-body-tab
    To workaround this issue in this .net project:
    - Suppress warning 1701 (Package not compatible)
    - Do not include nuget assets
    - Generate a property for this package so the path can be referenced
    - Copy the WINMD to the $(TargetDir) before the build starts
    - Feed the $(TargetDir)\WINMD path to CsWinRT in order to generate the projected classes
    NOTE: Suppressing the warning only is not enough as this will cause CoreClrInitFailure (0x80008089) error.
    -->
    <PackageReference Include="Microsoft.WindowsPackageManager.ComInterop" Version="1.11.550">
      <NoWarn>NU1701</NoWarn>
      <GeneratePathProperty>true</GeneratePathProperty>
      <IncludeAssets>none</IncludeAssets>
      <WindowsAppSdkUndockedRegFreeWinRTInitialize>false</WindowsAppSdkUndockedRegFreeWinRTInitialize>
    </PackageReference>

    <PackageReference Include="Microsoft.WindowsPackageManager.InProcCom" Version="1.11.550">
      <NoWarn>NU1701</NoWarn>
      <GeneratePathProperty>true</GeneratePathProperty>
      <IncludeAssets>none</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="CopyWinmdToTargetDir" BeforeTargets="BeforeBuild">
    <Copy SourceFiles="Microsoft.Management.Deployment.winmd" DestinationFolder="$(TargetDir)" />
  </Target>
</Project>