<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <PropertyGroup />
  <PropertyGroup>
    <ApplicationIcon>Icons\sUpdater.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyVersion>6.0.1.0</AssemblyVersion>
    <FileVersion>6.0.1.0</FileVersion>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Icons\updater_icon.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\getapps_icon.png" />
    <Resource Include="Icons\portable_icon.png" />
    <Resource Include="Icons\settings_icon.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\sUpdater.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\arrow_green.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\menu_icon.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\sUpdater.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Icons\no_icon.png" />
    <Resource Include="Icons\sUpdater_Grey.ico" />
    <Resource Include="Icons\sUpdater_Orange.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf">
      <Version>2.0.1</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Net.Http.Json">
      <Version>9.0.6</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowsPackageManager.Interop\WindowsPackageManager.Interop.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>